. '../.env'

DIGITALOCEAN_API_TOKEN=${DIGITALOCEAN_API_TOKEN}  DESKTOP_SSH="$DESKTOP_SSH"  GITHUB_PRIVATE_KEY="$GITHUB_PRIVATE_KEY"  GITHUB_PUBLIC_KEY="$GITHUB_PUBLIC_KEY"  vagrant up --provider=digital_ocean